### ISSUE TITLE
This repo does not seem to work anymore

### ISSUE THREAD

**Issue by kda-jt** [char/duo-hotp-export#1]
I just ran it on a freshly generated Duo QR code.
Failed with 

```
[src/main.rs:65:20] response = Object({
    "code": Number(
        40403,
    ),
    "message": String(
        "Unknown activation code",
    ),
    "stat": String(
        "FAIL",
    ),
})
thread 'main' panicked at src/main.rs:67:63:
called `Option::unwrap()` on a `None` value
```

**Comment by dverbru** [comment]
Before getting that error (which might be related to re-using the code), I got the following:

```
[src/main.rs:65:20] response = Object({
    "code": Number(
        40112,
    ),
    "message": String(
        "Signature type is not supported",
    ),
    "stat": String(
        "FAIL",
    ),
})
thread 'main' panicked at src/main.rs:67:63:
called `Option::unwrap()` on a `None` value
```
